apiVersion: apps/v1
kind: Deployment
metadata:
  name: keepalived-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keepalived-operator
  template:
    metadata:
      labels:
        name: keepalived-operator
    spec:
      serviceAccountName: keepalived-operator
      containers:
        - name: keepalived-operator
          # Replace this with the built image name
          image: quay.io/redhat-cop/keepalived-operator:v0.2.1
          command:
          - keepalived-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KEEPALIVED_OPERATOR_IMAGE_NAME
              value: quay.io/redhat-cop/keepalived-operator:v0.2.1
            - name: KEEPALIVEDGROUP_TEMPLATE_FILE_NAME
              value: /templates/keepalived-template.yaml                      
            - name: OPERATOR_NAME
              value: "keepalived-operator"
